<?php defined('BASEPATH') OR exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_admin extends CI_Model {
    function __construct() {
        parent::__construct();
        $this->load->database();
    }

    function tambah($table, $data) {
        $this->db->insert($table, $data);
    }

    function insert($table, $data) {
        $this->db->insert_batch($table, $data);
    }

    function update($where, $data, $table) {
        $this->db->where($where);
        $this->db->update($table, $data);
    }

    function hapus($table, $name_id, $id) {
        $this->db->where($name_id, $id);
        $this->db->delete($table);
    }

    function delete($table, $name_id, $id) {
        $this->db->where_in($name_id, $id);
        $this->db->delete($table);
    }

    function update_akun($f, $tb) {
        foreach ($f as $d) {
            $this->db->where('id_guru', $d['id_guru']);
            $u = $d['username_guru'];
            $p = $d['password'];
            $this->db->update($tb, ['username_guru' => $u, 'password' => $p]);
        }
    }

    // PENDIDIKAN

    function data_pendidikan() {
        $this->db->select('*');
        $this->db->from('tb_pendidikan');
        return $this->db->get();
    }

    // ADMIN

    function data_akun() {
        $this->db->select('*');
        $this->db->from('tb_akun');
        return $this->db->get();
    }

    function cekdata($id) {
        $this->db->where("id_akun", $id);
        return $this->db->get('tb_akun');
    }

    // SEKOLAH

    function data_sekolah() {
        $this->db->select('*');
        $this->db->from('tb_sekolah');
        return $this->db->get();
    }

    function get_sekolah() {
        $this->db->select('*');
        $this->db->from('tb_sekolah');
        return $this->db->get()->row();
    }

    // DATA EKSKUL

    function data_ekskul_siswa() {
        $this->db->select('*');
        $this->db->from('tb_ekskul_siswa');
        return $this->db->get();
    }

    // DATA KONDISI

    function data_kondisi() {
        $this->db->select('*');
        $this->db->from('tb_kondisi');
        return $this->db->get();
    }

    // GURU

    function data_guru() {
        return $this->db->query("SELECT * FROM tb_guru, tb_mapel WHERE tb_guru.jabatan = tb_mapel.id_mapel ORDER BY jabatan ASC ");
        // return $this->db->query("SELECT a.*, b.* FROM tb_guru a, tb_kelas b WHERE a.kelas = b.id_kelas ORDER BY th_jbkepsek DESC ");
    }

    // SISWA

    function data_siswa() {
        $this->db->select('*');
        $this->db->from('tb_siswa');
        $this->db->join('tb_kelas', 'kelas=id_kelas');
        return $this->db->get();
    }

    // MAPEL

    function data_mapel() {
        $this->db->select('*');
        $this->db->from('tb_mapel');
        return $this->db->get();
    }

    function mapel_id($id) {
        $hsl = $this->db->query("SELECT * FROM tb_mapel WHERE id_mapel='$id'");
        if ($hsl->num_rows() > 0) {
            foreach ($hsl->result() as $data) {
                $hasil = [
                    'id_mapel'   => $data->id_mapel,
                    'nm_mapel'   => $data->nm_mapel,
                    'kode_mapel' => $data->kode_mapel,
                    'ki_3'       => $data->ki_3,
                    'ki_4'       => $data->ki_4,
                ];
            }
        }
        return $hasil;
    }

    // KELAS

    function data_kelas() {
        $this->db->select('*');
        $this->db->from('tb_kelas');
        return $this->db->get();
    }

    // HARI

    function data_hari() {
        $this->db->select('*');
        $this->db->from('tb_hari');
        return $this->db->get();
    }

    // JADWAL

    function data_jadwal() {
        return $this->db->query("SELECT a.*, b.*, c.*, d.*, e.* FROM tb_jadwal a, tb_mapel b, tb_guru c, tb_kelas d, tb_hari e WHERE a.mapel = b.id_mapel AND a.guru = c.id_guru AND a.kelas = d.id_kelas AND a.hari = e.id_hari");
    }

    // DESKRIPSI KOMPETENSI

    function desk_ki3() {
        return $this->db->query("SELECT a.*, b.* FROM tb_desk_ki3 a, tb_mapel b WHERE a.mapel = b.id_mapel");
    }

    function desk_ki4() {
        return $this->db->query("SELECT a.*, b.* FROM tb_desk_ki4 a, tb_mapel b WHERE a.mapel = b.id_mapel");
    }

    // TAHUN AJARAN

    function data_tahunajaran() {
        $this->db->select('*');
        $this->db->from('tb_tahunajaran');
        return $this->db->get();
    }

    // SEMESTER

    function data_smt() {
        $this->db->select('*');
        $this->db->from('tb_smt');
        return $this->db->get();
    }

    // ABSEN

    function data_ab() {
        $this->db->select('*');
        $this->db->from('tb_ab');
        return $this->db->get();
    }

    function data_abguru() {
        $this->db->select('*');
        $this->db->from('tb_abguru');
        return $this->db->get();
    }

    function data_absiswa() {
        $this->db->select('*');
        $this->db->from('tb_absiswa');
        return $this->db->get();
    }

    // ORTU SISWA

    function data_ortu() {
        $this->db->select('*');
        $this->db->from('tb_ortu');
        return $this->db->get();
    }

    // FISIK

    function data_fisik() {
        $this->db->select('*');
        $this->db->from('tb_fisik');
        $this->db->join('tb_tahunajaran', 'id_tahunajaran=ta');
        return $this->db->get();
    }

    // KESEHATAN

    function data_kesehatan() {
        $this->db->select('*');
        $this->db->from('tb_kesehatan');
        return $this->db->get();
    }

    // EKSKUL

    function data_ekskul() {
        $this->db->select('*');
        $this->db->from('tb_ekskul');
        return $this->db->get();
    }

    // PRESTASI

    function data_prestasi() {
        $this->db->select('*');
        $this->db->from('tb_prestasi');
        return $this->db->get();
    }

    // SIKAP

    function data_sikap_ki1() {
        $this->db->select('*');
        $this->db->from('tb_sikap_ki1');
        $this->db->join('tb_siswa', 'siswa = id_siswa');
        return $this->db->get();
    }

    function data_sikap_ki2() {
        $this->db->select('*');
        $this->db->from('tb_sikap_ki2');
        $this->db->join('tb_siswa', 'siswa = id_siswa');
        return $this->db->get();
    }

    function data_kr_ki3() {
        $this->db->select('*');
        $this->db->from('tb_kr_ki3');
        return $this->db->get();
    }

    function data_kr_ki4() {
        $this->db->select('*');
        $this->db->from('tb_kr_ki4');
        return $this->db->get();
    }

    function naik_kelas($arr, $table) {
        foreach ($arr as $d) {
            $this->db->where('id_siswa', $d['id_siswa']);
            $data = $this->db->get($table)->row();
            $kl   = $data->kelas + 1;
            $this->db->where('id_siswa', $d['id_siswa']);
            $this->db->update($table, ['kelas' => $kl]);
        }
    }

    function turun_kelas($arr, $table) {
        foreach ($arr as $d) {
            $this->db->where('id_siswa', $d['id_siswa']);
            $data = $this->db->get($table)->row();
            $kl   = $data->kelas - 1;
            $this->db->where('id_siswa', $d['id_siswa']);
            $this->db->update($table, ['kelas' => $kl]);
        }
    }
}
?>
