<?php defined('BASEPATH') OR exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_guru extends CI_Model {
    function __construct() {
        parent::__construct();
        $this->load->database();
    }

    // GURU

    function data_guru() {
        $this->db->select('*');
        $this->db->from('tb_guru');
        return $this->db->get();
    }

    function cekdata($id) {
        $this->db->where("id_guru", $id);
        return $this->db->get('tb_guru');
    }

}
?>
