<?php defined('BASEPATH') OR exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_login extends CI_Model {
    function __construct() {
        parent::__construct();
        $this->load->database();
    }

    // ADMIN

    public function cekakun($table, $field, $id) {
        $res = $this->db->query("SELECT * FROM " . $table . " WHERE " . $field . "='" . $id . "'");
        return $res->result_array();
    }

}
?>
